name: 'AWS Deploy S3 File Sample'

on:
  push:
    branches:
      - 'main'

jobs:
  sample:
    name: sample
    runs-on: ubuntu-latest
    steps:
      - name: Create a static folder & file
        run: mkdir codedeploy-demo 
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_S3_REGION }}
      - name: Deploy static files to AWS S3
        id: devops-with-aws
        uses: RohiniAlla/devops-with-aws@main
        with:
          region: ${{ secrets.AWS_S3_REGION }}
          bucket: ${{ secrets.AWS_S3_BUCKET }}
          source: '.'
          target: 'codedeploy-demo/app.zip'
      - name: deploy to S3
        run: |
             aws deploy push --application-name CodeDeployDemo --s3-location s3://aws-devops-cicddemo/codedeploy-demo/app.zip --ignore-hidden-files --region us-east-2 --profile aws-devops
        #aws s3 sync . s3://aws-devops-cicddemo1 --profile aws-devops --region us-east-2 --delete --exclude ".git/*" --exclude ".github/*"
          
