
name: Upload to S3

on:
  push:
    branches:
      - main

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: actions/checkout@v2
      with:
        aws-access-key-id: AKIA2SB2U2MGUC6DKP2C
        aws-secret-access-key: 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
        aws-region: us-east-2

    - name: Install AWS CLI
      run: |
        sudo apt-get update && sudo apt-get install -y awscli
    - name: Sync to S3
      run: |
        aws s3 sync . s3://aws-devops-cicddemo1 --region us-east-2 --delete --exclude ".git/*" --exclude ".github/*"
