
name: Upload to S3

on:
  push:
    branches:
      - main

jobs:
  upload:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: actions/checkout@v2
      with:
        #aws-access-key-id: 
        #aws-secret-access-key: 
        aws-region: us-east-2
        #aws-output

    - name: Install AWS CLI
      run: |
        sudo apt-get update && sudo apt-get install -y awscli
    - name: list prifiles
      run: |
        aws configure list-profiles
    - name: Sync to S3
      run: |
        aws s3 sync . s3://aws-devops-cicddemo1 --profile aws-devops --region us-east-2 --delete --exclude ".git/*" --exclude ".github/*"
